# w PGAdmin jako server trzeba podac nazwe kontenera
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=projekt
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    networks:
      - pgnetwork

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - '80:80'
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge